export const Strings = {
  topHeader: 'top achievers july 2022 ',
  header: 'kisan ekta samaj sangathan',
  leaderBoardUpdateDescription: 'The leaderboard will update every midnight',
  noLiveEvent: 'There are no live events now',
  header1: 'Weekly Summit and Audit by Our Guest Swami Shankar',
  liveOntime1: 'On 23 Oct, 5:30 PM',
  live: 'LIVE',
  name1: 'Dipankar Mukherjee Biswas',
  designation1: 'General Secretary - Noida, Uttar Pradesh',
  eventHost: 'EVENT HOST',
  ourSpeakers: 'OUR SPEAKERS',
  startLiveNow: 'START LIVE NOW',
  viewEvent: 'View Event',
  aanchal: 'Anchal Srivastava',
  anchalDesignation: 'State President | Noida, Uttar Pradesh',
  akansha: 'Akansha',
  akanshaDesignation: 'National President',
  krishna: 'Krishi Mahajan',
  krishnaDesignation: 'GUEST',
  reactions: 1,
  comments: 11,
  attending: 'Attending',
  loved: 'Loved',
  comment: 'Comment',
  share: 'Share',
  reactionText: 'Reactions',
  commentText: 'Comments',
  hash: '#',
};
